// Generated by CoffeeScript 2.7.0
(function() {
  // app.coffee — Entry point, UI controls, circle config, custom scale editor
  var SIDE_COUNTERPART, STORAGE_KEY;

  STORAGE_KEY = 'slide-rule-settings';

  // D/C and A/B are conventionally paired across the inner/outer (circular) —
  // equivalently top/bottom-facing (flat) — divide: D and A face outward, C
  // and B face inward. Picking one for the wrong side means the user actually
  // wants its counterpart there.
  SIDE_COUNTERPART = {
    D: 'C',
    C: 'D',
    A: 'B',
    B: 'A'
  };

  this.App = class App {
    constructor() {
      var RulerClass;
      this.canvas = document.getElementById('ruler');
      this.allScales = BUILTIN_SCALES.slice();
      this.config = this._defaultConfig();
      this.editingScale = null;
      this._loadState();
      RulerClass = this.flatMode ? FlatRuler : CircularRuler;
      this.ruler = new RulerClass(this.canvas, this.config);
      this._attachRuler(this.ruler);
      this._setupUI();
      this._renderPanel();
      this.ruler.resize();
      this._updateReadout();
      // A backgrounded/frozen tab can come back to the foreground (task
      // switcher resume, WebAPK task reuse) with its canvas left stale or
      // blank, since the canvas only gets redrawn on a 'resize' event or at
      // initial load. Force a fresh layout + redraw whenever the page becomes
      // visible again to guard against that.
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') {
          return this.ruler.resize();
        }
      });
      window.addEventListener('pageshow', () => {
        return this.ruler.resize();
      });
    }

    // Wire a (re)created ruler instance's callbacks. Shared by the initial
    // construction and by flat/circular mode switching, so both paths stay
    // in sync instead of duplicating this wiring.
    _attachRuler(ruler) {
      ruler.onCursorMove = () => {
        return this._updateReadout();
      };
      ruler.onCircleRotate = () => {
        this._updateReadout();
        return this._saveState();
      };
      return ruler.onGlobalRotate = () => {
        this._updateReadout();
        return this._saveState();
      };
    }

    _loadState() {
      var byLabel, data, def, e, j, k, l, len, len1, len2, newConfig, raw, ref, ref1, ref2, ring, s, scale;
      try {
        raw = localStorage.getItem(STORAGE_KEY);
        if (!raw) {
          return;
        }
        data = JSON.parse(raw);
      } catch (error) {
        e = error;
        console.warn('Failed to load settings:', e);
        return;
      }
      // Restore custom scales
      if (data.customScales) {
        ref = data.customScales;
        for (j = 0, len = ref.length; j < len; j++) {
          def = ref[j];
          scale = new Scale(def);
          if (!scale.error) {
            this.allScales.push(scale);
          }
        }
      }
      // Restore ring config
      if (data.rings) {
        byLabel = {};
        ref1 = this.allScales;
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          s = ref1[k];
          byLabel[s.label] = s;
        }
        newConfig = [];
        ref2 = data.rings;
        for (l = 0, len2 = ref2.length; l < len2; l++) {
          ring = ref2[l];
          newConfig.push({
            inner: ring.inner ? byLabel[ring.inner] || null : null,
            outer: ring.outer ? byLabel[ring.outer] || null : null,
            rotatable: ring.rotatable || false,
            rotation: ring.rotation || 0
          });
        }
        if (newConfig.length > 0) {
          this.config = newConfig;
        }
      }
      // Restore minTickAngle
      if (data.minTickAngle != null) {
        this.minTickAngle = data.minTickAngle;
      }
      // Restore offCenter
      if (data.offCenter != null) {
        this.offCenter = data.offCenter;
      }
      // Restore globalRotation
      if (data.globalRotation != null) {
        this.globalRotation = data.globalRotation;
      }
      // Restore darkMode
      if (data.darkMode != null) {
        this.darkMode = data.darkMode;
      }
      // Restore flatMode
      if (data.flatMode != null) {
        return this.flatMode = data.flatMode;
      }
    }

    // Default ring configuration
    // Each ring: {inner: Scale|null, outer: Scale|null, rotatable: bool, rotation: 0}
    _defaultConfig() {
      return [
        {
          inner: this._scaleByLabel('C'),
          outer: null,
          rotatable: true,
          rotation: 0
        },
        {
          inner: null,
          outer: this._scaleByLabel('D'),
          rotatable: false,
          rotation: 0
        }
      ];
    }

    // Re-render canvas, panel and readout, then persist state
    _refresh(relayout = false) {
      if (relayout) {
        this.ruler.resize();
      } else {
        this.ruler.render();
      }
      this._renderPanel();
      this._updateReadout();
      return this._saveState();
    }

    _saveState() {
      var data, e, s;
      try {
        data = {
          rings: this.config.map(function(ring) {
            return {
              inner: ring.inner ? ring.inner.label : null,
              outer: ring.outer ? ring.outer.label : null,
              rotatable: ring.rotatable,
              rotation: ring.rotation
            };
          }),
          customScales: (function() {
            var j, len, ref, results1;
            ref = this.allScales;
            results1 = [];
            for (j = 0, len = ref.length; j < len; j++) {
              s = ref[j];
              if (!s.builtin) {
                results1.push(s.toJSON());
              }
            }
            return results1;
          }).call(this),
          minTickAngle: this.ruler.minTickAngle || 3,
          offCenter: this.ruler.offCenter || false,
          globalRotation: this.ruler.globalRotation || 0,
          darkMode: this.ruler.darkMode || false,
          flatMode: this.flatMode || false
        };
        return localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
      } catch (error) {
        e = error;
        return console.warn('Failed to save settings:', e);
      }
    }

    _setupUI() {
      var addBtn, addRingBtn, closeBtn, darkModeInput, exportBtn, flatModeInput, importBtn, minAngleInput, minAngleVal, offCenterInput, panel, preciseToggle, resetBtn, toggleBtn;
      // Toggle panel
      toggleBtn = document.getElementById('toggle-panel');
      panel = document.getElementById('panel');
      closeBtn = document.getElementById('close-panel');
      toggleBtn.addEventListener('click', () => {
        return panel.classList.toggle('hidden');
      });
      closeBtn.addEventListener('click', () => {
        return panel.classList.add('hidden');
      });
      // Reset
      resetBtn = document.getElementById('reset');
      resetBtn.addEventListener('click', () => {
        return this._reset();
      });
      // Precise mode toggle: slows ring/cursor rotation to 1/10 speed for
      // finer control, especially useful on touchscreens.
      preciseToggle = document.getElementById('precise-toggle');
      this.ruler.precise = false;
      preciseToggle.addEventListener('click', () => {
        this.ruler.precise = !this.ruler.precise;
        return preciseToggle.classList.toggle('active', this.ruler.precise);
      });
      // Add custom scale
      addBtn = document.getElementById('add-scale');
      addBtn.addEventListener('click', () => {
        return this._addCustomScale();
      });
      // Add ring
      addRingBtn = document.getElementById('add-ring');
      addRingBtn.addEventListener('click', () => {
        return this._addRing();
      });
      // Min tick angle slider
      minAngleInput = document.getElementById('min-tick-angle');
      minAngleVal = document.getElementById('min-tick-angle-val');
      // Restore minTickAngle from saved state
      if (this.minTickAngle != null) {
        this.ruler.minTickAngle = this.minTickAngle;
        minAngleInput.value = this.minTickAngle;
        minAngleVal.textContent = this.minTickAngle;
      }
      minAngleInput.addEventListener('input', (e) => {
        this.ruler.minTickAngle = parseFloat(e.target.value);
        minAngleVal.textContent = e.target.value;
        this.ruler.render();
        return this._saveState();
      });
      // Off-center layout toggle
      offCenterInput = document.getElementById('off-center');
      if (this.offCenter != null) {
        this.ruler.offCenter = this.offCenter;
      }
      offCenterInput.classList.toggle('active', this.ruler.offCenter);
      offCenterInput.addEventListener('click', () => {
        this.ruler.offCenter = !this.ruler.offCenter;
        offCenterInput.classList.toggle('active', this.ruler.offCenter);
        this.ruler.resize();
        return this._saveState();
      });
      if (this.globalRotation != null) {
        this.ruler.globalRotation = this.globalRotation;
      }
      // Dark mode toggle
      darkModeInput = document.getElementById('dark-mode');
      if (this.darkMode != null) {
        this.ruler.darkMode = this.darkMode;
      }
      darkModeInput.classList.toggle('active', this.ruler.darkMode);
      document.body.classList.toggle('dark', this.ruler.darkMode);
      darkModeInput.addEventListener('click', () => {
        this.ruler.darkMode = !this.ruler.darkMode;
        darkModeInput.classList.toggle('active', this.ruler.darkMode);
        document.body.classList.toggle('dark', this.ruler.darkMode);
        this.ruler.render();
        return this._saveState();
      });
      // Flat ruled mode toggle: swaps the whole renderer (CircularRuler <->
      // FlatRuler) rather than a rendering flag, since the two share only the
      // data model (config/cursorAngle/globalRotation), not the drawing or
      // pointer-interaction math.
      flatModeInput = document.getElementById('flat-mode');
      flatModeInput.classList.toggle('active', this.flatMode || false);
      flatModeInput.addEventListener('click', () => {
        var RulerClass, oldRuler;
        this.flatMode = !this.flatMode;
        flatModeInput.classList.toggle('active', this.flatMode);
        oldRuler = this.ruler;
        RulerClass = this.flatMode ? FlatRuler : CircularRuler;
        this.ruler = new RulerClass(this.canvas, this.config);
        this.ruler.cursorAngle = oldRuler.cursorAngle;
        this.ruler.globalRotation = oldRuler.globalRotation;
        this.ruler.darkMode = oldRuler.darkMode;
        this.ruler.minTickAngle = oldRuler.minTickAngle;
        this.ruler.precise = oldRuler.precise;
        if (oldRuler.offCenter != null) {
          this.ruler.offCenter = oldRuler.offCenter;
        }
        this._attachRuler(this.ruler);
        this.ruler.resize();
        this._updateReadout();
        return this._saveState();
      });
      // Export
      exportBtn = document.getElementById('export-scales');
      exportBtn.addEventListener('click', () => {
        return this._exportScales();
      });
      // Import
      importBtn = document.getElementById('import-scales');
      importBtn.addEventListener('click', () => {
        return this._importScales();
      });
      // Resize
      return window.addEventListener('resize', () => {
        return this.ruler.resize();
      });
    }

    _reset() {
      this.config = this._defaultConfig();
      this.ruler.config = this.config;
      this.ruler.cursorAngle = 0;
      this.ruler.globalRotation = 0;
      return this._refresh();
    }

    _addCustomScale() {
      var candidate, color, decadesVal, formula, label, maxVal, minVal;
      label = document.getElementById('scale-label').value.trim();
      formula = document.getElementById('scale-formula').value.trim();
      minVal = parseFloat(document.getElementById('scale-min').value);
      maxVal = parseFloat(document.getElementById('scale-max').value);
      decadesVal = parseFloat(document.getElementById('scale-decades').value);
      color = document.getElementById('scale-color').value;
      if (!(label && formula)) {
        alert('Label and formula are required');
        return;
      }
      if (!(isFinite(minVal) && isFinite(maxVal))) {
        alert('Valid min and max values are required');
        return;
      }
      if (!(maxVal > minVal)) {
        alert('Max must be greater than min');
        return;
      }
      candidate = new Scale({
        label: label,
        formula: formula,
        range: [minVal, maxVal],
        decades: isFinite(decadesVal) ? decadesVal : null,
        color: color,
        builtin: false
      });
      if (candidate.error) {
        alert('Scale error: ' + candidate.error);
        return;
      }
      if (this.editingScale != null) {
        // Mutate the existing object so ring references stay valid
        this.editingScale.label = candidate.label;
        this.editingScale.formula = candidate.formula;
        this.editingScale.range = candidate.range;
        this.editingScale.decades = candidate.decades;
        this.editingScale.decadesAuto = candidate.decadesAuto;
        this.editingScale.color = candidate.color;
        this.editingScale.fn = candidate.fn;
        this.editingScale.error = null;
      } else {
        this.allScales.push(candidate);
      }
      this._clearScaleForm();
      return this._refresh();
    }

    _editScale(index) {
      var scale;
      scale = this.allScales[index];
      if (scale.builtin) {
        return;
      }
      this.editingScale = scale;
      document.getElementById('scale-label').value = scale.label;
      document.getElementById('scale-formula').value = scale.formula;
      document.getElementById('scale-min').value = scale.range[0];
      document.getElementById('scale-max').value = scale.range[1];
      document.getElementById('scale-decades').value = scale.decadesAuto ? '' : scale.decades;
      document.getElementById('scale-color').value = scale.color;
      return document.getElementById('add-scale').textContent = 'Save Scale';
    }

    _clearScaleForm() {
      this.editingScale = null;
      document.getElementById('scale-label').value = '';
      document.getElementById('scale-formula').value = '';
      document.getElementById('scale-min').value = '';
      document.getElementById('scale-max').value = '';
      document.getElementById('scale-decades').value = '';
      return document.getElementById('add-scale').textContent = '+ Add Scale';
    }

    _deleteScale(index) {
      var j, len, ref, ring, scale;
      scale = this.allScales[index];
      if (scale.builtin) {
        return;
      }
      if (this.editingScale === scale) {
        this._clearScaleForm();
      }
      this.allScales.splice(index, 1);
      ref = this.config;
      // Remove from all rings
      for (j = 0, len = ref.length; j < len; j++) {
        ring = ref[j];
        if (ring.inner === scale) {
          ring.inner = null;
        }
        if (ring.outer === scale) {
          ring.outer = null;
        }
      }
      return this._refresh();
    }

    _addRing() {
      this.config.unshift({
        inner: null,
        outer: null,
        rotatable: false,
        rotation: 0
      });
      return this._refresh(true);
    }

    _removeRing(index) {
      this.config.splice(index, 1);
      return this._refresh(true);
    }

    _setRingScale(ringIndex, side, label) {
      var scale, swapLabel, swapScale;
      scale = this._scaleByLabel(label);
      if ((scale != null) && scale.side && scale.side !== side) {
        swapLabel = SIDE_COUNTERPART[scale.label];
        swapScale = swapLabel ? this._scaleByLabel(swapLabel) : null;
        if (swapScale != null) {
          scale = swapScale;
        }
      }
      this.config[ringIndex][side] = scale || null;
      return this._refresh();
    }

    _scaleByLabel(label) {
      var j, len, ref, s;
      ref = this.allScales;
      for (j = 0, len = ref.length; j < len; j++) {
        s = ref[j];
        if (s.label === label) {
          return s;
        }
      }
      return null;
    }

    _toggleRingRotatable(index) {
      var ring;
      ring = this.config[index];
      ring.rotatable = !ring.rotatable;
      this.ruler.render();
      this._renderPanel();
      return this._saveState();
    }

    _exportScales() {
      var data, textarea;
      textarea = document.getElementById('io-textarea');
      data = JSON.stringify(this.allScales.map(function(s) {
        return s.toJSON();
      }), null, 2);
      return textarea.value = data;
    }

    _importScales() {
      var builtins, data, def, e, imported, j, len, s, scale, textarea;
      textarea = document.getElementById('io-textarea');
      try {
        data = JSON.parse(textarea.value);
      } catch (error) {
        e = error;
        alert('Invalid JSON: ' + e.message);
        return;
      }
      if (!Array.isArray(data)) {
        alert('Expected an array of scale definitions');
        return;
      }
      imported = [];
      for (j = 0, len = data.length; j < len; j++) {
        def = data[j];
        scale = new Scale(def);
        if (scale.error) {
          alert('Scale "' + (def.label || '?') + '" error: ' + scale.error);
          continue;
        }
        imported.push(scale);
      }
      if (imported.length === 0) {
        alert('No valid scales to import');
        return;
      }
      // Keep built-ins and replace custom scales with the imported set
      builtins = (function() {
        var k, len1, ref, results1;
        ref = this.allScales;
        results1 = [];
        for (k = 0, len1 = ref.length; k < len1; k++) {
          s = ref[k];
          if (s.builtin) {
            results1.push(s);
          }
        }
        return results1;
      }).call(this);
      this.allScales = builtins.concat(imported);
      return this._refresh();
    }

    _renderPanel() {
      this._renderRingList();
      return this._renderScaleList();
    }

    _renderRingList() {
      var container, controls, current, dot, header, i, item, j, k, l, len, len1, len2, noneOpt, opt, ref, ref1, ref2, removeBtn, results1, ring, scale, select, side, slot, slotLabel, slotsDiv, title, toggle;
      container = document.getElementById('circle-list');
      container.innerHTML = '';
      ref = this.config;
      results1 = [];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        ring = ref[i];
        item = document.createElement('div');
        item.className = 'circle-item';
        header = document.createElement('div');
        header.className = 'circle-item-header';
        title = document.createElement('span');
        title.textContent = 'Ring ' + (this.config.length - i) + (ring.rotatable ? ' (rotatable)' : ' (fixed)');
        controls = document.createElement('div');
        controls.className = 'circle-item-controls';
        toggle = document.createElement('div');
        toggle.className = 'toggle-switch' + (ring.rotatable ? ' active' : '');
        toggle.dataset.ringIndex = i.toString();
        toggle.addEventListener('click', (e) => {
          return this._toggleRingRotatable(parseInt(e.currentTarget.dataset.ringIndex));
        });
        removeBtn = document.createElement('button');
        removeBtn.className = 'circle-item-remove';
        removeBtn.textContent = '✕';
        removeBtn.title = 'Remove ring';
        removeBtn.dataset.ringIndex = i.toString();
        removeBtn.addEventListener('click', (e) => {
          return this._removeRing(parseInt(e.currentTarget.dataset.ringIndex));
        });
        controls.appendChild(toggle);
        controls.appendChild(removeBtn);
        header.appendChild(title);
        header.appendChild(controls);
        item.appendChild(header);
        slotsDiv = document.createElement('div');
        slotsDiv.className = 'ring-slots';
        ref1 = ['outer', 'inner'];
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          side = ref1[k];
          slot = document.createElement('div');
          slot.className = 'ring-slot';
          slotLabel = document.createElement('span');
          slotLabel.className = 'ring-slot-label';
          slotLabel.textContent = side === 'outer' ? 'Outer' : 'Inner';
          slot.appendChild(slotLabel);
          dot = document.createElement('span');
          dot.className = 'dot';
          current = ring[side];
          dot.style.background = current ? current.color : 'transparent';
          slot.appendChild(dot);
          select = document.createElement('select');
          select.className = 'ring-slot-select';
          select.dataset.ring = i.toString();
          select.dataset.side = side;
          noneOpt = document.createElement('option');
          noneOpt.value = '';
          noneOpt.textContent = '— none —';
          select.appendChild(noneOpt);
          ref2 = this.allScales;
          for (l = 0, len2 = ref2.length; l < len2; l++) {
            scale = ref2[l];
            opt = document.createElement('option');
            opt.value = scale.label;
            opt.textContent = scale.label;
            if (current === scale) {
              opt.selected = true;
            }
            select.appendChild(opt);
          }
          select.addEventListener('change', (e) => {
            return this._setRingScale(parseInt(e.target.dataset.ring), e.target.dataset.side, e.target.value);
          });
          slot.appendChild(select);
          slotsDiv.appendChild(slot);
        }
        item.appendChild(slotsDiv);
        results1.push(container.appendChild(item));
      }
      return results1;
    }

    _renderScaleList() {
      var container, delBtn, dot, editBtn, formula, i, item, j, len, name, ref, results1, scale;
      container = document.getElementById('scale-list');
      container.innerHTML = '';
      ref = this.allScales;
      results1 = [];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        scale = ref[i];
        item = document.createElement('div');
        item.className = 'scale-item';
        if (scale.error) {
          item.classList.add('error');
        }
        dot = document.createElement('span');
        dot.className = 'dot';
        dot.style.background = scale.color;
        item.appendChild(dot);
        name = document.createElement('span');
        name.className = 'name';
        name.textContent = scale.label;
        item.appendChild(name);
        formula = document.createElement('span');
        formula.className = 'formula';
        formula.textContent = scale.formula;
        item.appendChild(formula);
        // Edit and delete buttons (only for custom scales)
        if (!scale.builtin) {
          editBtn = document.createElement('button');
          editBtn.textContent = '✎';
          editBtn.title = 'Edit scale';
          editBtn.dataset.scaleIndex = i.toString();
          editBtn.addEventListener('click', (e) => {
            return this._editScale(parseInt(e.currentTarget.dataset.scaleIndex));
          });
          item.appendChild(editBtn);
          delBtn = document.createElement('button');
          delBtn.textContent = '✕';
          delBtn.title = 'Delete scale';
          delBtn.dataset.scaleIndex = i.toString();
          delBtn.addEventListener('click', (e) => {
            return this._deleteScale(parseInt(e.currentTarget.dataset.scaleIndex));
          });
          item.appendChild(delBtn);
        }
        results1.push(container.appendChild(item));
      }
      return results1;
    }

    _updateReadout() {
      var container, j, labelSpan, len, r, results, results1, row, valSpan;
      container = document.getElementById('readout-values');
      results = this.ruler.readAtCursor();
      container.innerHTML = '';
      if (results.length === 0) {
        container.innerHTML = '<span style="color:#666">No scales at cursor</span>';
        return;
      }
      results1 = [];
      for (j = 0, len = results.length; j < len; j++) {
        r = results[j];
        row = document.createElement('div');
        row.className = 'readout-row';
        labelSpan = document.createElement('span');
        labelSpan.className = 'readout-label';
        labelSpan.style.color = r.scale.color;
        labelSpan.textContent = r.scale.label;
        row.appendChild(labelSpan);
        valSpan = document.createElement('span');
        valSpan.className = 'readout-value';
        valSpan.textContent = this._formatValue(r.value, r.scale);
        row.appendChild(valSpan);
        results1.push(container.appendChild(row));
      }
      return results1;
    }

    _formatValue(value, scale) {
      if (scale.formula.indexOf('sin') >= 0 || scale.formula.indexOf('tan') >= 0) {
        return value.toFixed(2) + '°';
      } else if (value >= 1000) {
        return value.toExponential(3);
      } else if (value >= 100) {
        return value.toFixed(1);
      } else if (value >= 10) {
        return value.toFixed(2);
      } else if (value >= 1) {
        return value.toFixed(3);
      } else {
        return value.toFixed(4);
      }
    }

  };

  // Boot
  window.addEventListener('DOMContentLoaded', function() {
    var hadController, reloading, showUpdateButton, updateBtn;
    window.app = new App();
    // Register service worker (offline-first: the app always loads instantly
    // from cache; updates are fetched in the background and applied only once
    // the user confirms via the "update available" button).
    if ('serviceWorker' in navigator) {
      // Only auto-reload on a *later* activation, not this page's first install
      hadController = !!navigator.serviceWorker.controller;
      updateBtn = document.getElementById('update-available');
      showUpdateButton = function(reg) {
        updateBtn.classList.remove('hidden');
        return updateBtn.onclick = function() {
          var ref;
          updateBtn.disabled = true;
          return (ref = reg.waiting) != null ? ref.postMessage('skipWaiting') : void 0;
        };
      };
      navigator.serviceWorker.register('sw.js').then(function(reg) {
        if (reg.waiting && hadController) {
          // A worker may already be waiting if this page loaded right after an
          // update was fetched elsewhere
          showUpdateButton(reg);
        }
        reg.addEventListener('updatefound', function() {
          var newWorker;
          newWorker = reg.installing;
          if (newWorker == null) {
            return;
          }
          return newWorker.addEventListener('statechange', function() {
            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
              return showUpdateButton(reg);
            }
          });
        });
        // Check for a newer version whenever the app regains focus, since a
        // PWA is often reopened from a home-screen icon after a long time away
        return document.addEventListener('visibilitychange', function() {
          if (document.visibilityState === 'visible') {
            return reg.update();
          }
        });
      }).catch(function(err) {
        return console.warn('Service worker registration failed:', err);
      });
      // Once the user-confirmed update finishes activating, reload once to
      // pick up the new cached assets.
      reloading = false;
      return navigator.serviceWorker.addEventListener('controllerchange', function() {
        if (reloading || !hadController) {
          return;
        }
        reloading = true;
        return window.location.reload();
      });
    }
  });

}).call(this);
