// Generated by CoffeeScript 2.7.0
(function() {
  // ruler.coffee — Canvas rendering + pointer interaction for circular and flat slide rules

  // Canvas color palette for the current display mode. True black background
  // in dark mode (not dark gray) since this is meant for OLED screens, where
  // black pixels are actually off. Shared by CircularRuler and FlatRuler.
  var FLAT_MARGIN_FRACTION, FLAT_MIN_TICK_PX, formatTickLabel, themeFor;

  themeFor = function(darkMode) {
    if (darkMode) {
      return {
        bg: '#000',
        bgBorder: '#555',
        ringBorder: '#444',
        ringShade: 'rgba(255,255,255,0.04)'
      };
    } else {
      return {
        bg: '#fff',
        bgBorder: '#999',
        ringBorder: '#bbb',
        ringShade: 'rgba(0,0,0,0.02)'
      };
    }
  };

  // FlatRuler shows a bit more than one full decade at zero rotation (e.g.
  // ~0.9-11 for a 1-10 scale) rather than cutting the pattern off flush with
  // the screen edges, since a tick landing exactly on the edge is hard to
  // read. Expressed as a fraction of one decade's width, padded on each side.
  FLAT_MARGIN_FRACTION = 0.045;

  // Minimum pixel gap between adjacent minor ticks in FlatRuler. Below this,
  // thin out subdivisions (same mechanism the circular ruler already uses —
  // generateTicks(minAngle) — just with minAngle raised so it stays
  // meaningful when a decade's pixel width is small) rather than keep drawing
  // ticks too close together to tell apart. Less precise on narrow screens,
  // but legible, instead of stretching the band past the viewport.
  FLAT_MIN_TICK_PX = 3;

  formatTickLabel = function(value, scale) {
    if (scale.formula.indexOf('sin') >= 0 || scale.formula.indexOf('tan') >= 0) {
      if (value < 1) {
        return value.toFixed(2) + '°';
      } else if (value < 10) {
        return value.toFixed(1) + '°';
      } else {
        return Math.round(value).toString() + '°';
      }
    } else if (scale.formula.indexOf('log10') >= 0 || scale.formula.indexOf('log(') >= 0) {
      // Log scales: integers without trailing zeros
      if (value >= 1) {
        return Math.round(value).toString();
      } else {
        // Sub-1 values (e.g. sqrt scale): show with one decimal
        return value.toFixed(1);
      }
    } else {
      // Linear and other scales: no non-significant trailing zeros
      if (value >= 100) {
        return Math.round(value).toString();
      } else if (value >= 10) {
        return value.toFixed(0);
      } else if (value >= 1) {
        return parseFloat(value.toFixed(1)).toString();
      } else {
        return parseFloat(value.toFixed(2)).toString();
      }
    }
  };

  this.CircularRuler = class CircularRuler {
    constructor(canvas, config) {
      this.canvas = canvas;
      this.ctx = canvas.getContext('2d');
      this.config = config; // array of circle objects
      this.cursorAngle = 0; // degrees, 0 = top (12 o'clock)
      this.globalRotation = 0; // degrees, applied on top of every ring's own rotation
      this.dpr = window.devicePixelRatio || 1;
      this.width = 0;
      this.height = 0;
      this.cx = 0;
      this.cy = 0;
      this.offCenter = false; // display option: shift center left for phone screens
      this.outerRadius = 0;
      this.ringWidth = 0;
      this.dragging = null; // {type: 'circle'|'cursor'|'global', index, startAngle, startRotation}
      this.darkMode = false; // display option: true black background for OLED
      this.onCursorMove = null; // callback(angle)
      this.onCircleRotate = null; // callback(index, angle)
      this.onGlobalRotate = null; // callback(angle)
      this._bindEvents();
      this.resize();
    }

    resize() {
      var holeR, lastHasBoth, lastRing, minHoleR, nCircles;
      this.width = window.innerWidth;
      this.height = window.innerHeight;
      // On some WebView launches (notably WebAPK cold starts) the viewport
      // briefly reports 0x0 before layout settles. Rendering with that would
      // throw (negative radius) and, since no further real resize event
      // follows, leave the canvas permanently blank. Retry on the next frame
      // instead until real dimensions are available.
      if (this.width <= 0 || this.height <= 0) {
        requestAnimationFrame(() => {
          return this.resize();
        });
        return;
      }
      this.canvas.style.width = this.width + 'px';
      this.canvas.style.height = this.height + 'px';
      this.canvas.width = this.width * this.dpr;
      this.canvas.height = this.height * this.dpr;
      this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      if (this.offCenter) {
        if (this.width >= this.height) {
          // Landscape: the controls/readout sit at the side, so shift the
          // ruler toward the bottom quarter instead of the left quarter
          // (which would be portrait's off-center direction).
          this.cx = this.width / 2;
          this.cy = this.height * 3 / 4;
          this.outerRadius = Math.max(0, Math.min(this.height * 0.75, this.width / 2 - 8));
        } else {
          this.cx = this.width / 4;
          this.cy = this.height / 2;
          this.outerRadius = Math.max(0, Math.min(this.width * 0.75, this.height / 2 - 8));
        }
      } else {
        this.cx = this.width / 2;
        this.cy = this.height / 2;
        this.outerRadius = Math.max(0, Math.min(this.width, this.height) / 2 - 8);
      }
      nCircles = this.config.length;
      this.ringWidth = this.outerRadius / (nCircles * 1.5 + 1);
      // The innermost ring's inner edge borders the empty center (not another
      // ring), so unlike every other ring it can grow into that space if it
      // needs the extra room — e.g. it carries two scales — without disturbing
      // any other ring's layout. Only borrow from the center when necessary,
      // and never past a small minimum so a pivot area always remains.
      lastRing = this.config[nCircles - 1];
      lastHasBoth = (lastRing != null) && (lastRing.outer != null) && lastRing.outer.visible !== false && (lastRing.inner != null) && lastRing.inner.visible !== false;
      holeR = this.outerRadius - nCircles * this.ringWidth;
      minHoleR = this.ringWidth * 0.6;
      this.lastRingExtra = lastHasBoth ? Math.max(0, Math.min(this.ringWidth * 0.6, holeR - minHoleR)) : 0;
      return this.render();
    }

    // Get radius range for a circle index
    circleRadii(index) {
      var extra, innerR, outerR;
      outerR = this.outerRadius - index * this.ringWidth;
      extra = index === this.config.length - 1 ? this.lastRingExtra || 0 : 0;
      innerR = outerR - this.ringWidth - extra;
      return {
        outer: outerR,
        inner: innerR
      };
    }

    _theme() {
      return themeFor(this.darkMode);
    }

    render() {
      var circle, ctx, i, j, len, ref, theme;
      ctx = this.ctx;
      theme = this._theme();
      ctx.clearRect(0, 0, this.width, this.height);
      // Draw background circle
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, this.outerRadius + 4, 0, 2 * Math.PI);
      ctx.fillStyle = theme.bg;
      ctx.fill();
      ctx.strokeStyle = theme.bgBorder;
      ctx.lineWidth = 1;
      ctx.stroke();
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        this._drawCircle(i, circle);
      }
      return this._drawCursor();
    }

    _drawCircle(index, circle) {
      var ctx, hasBoth, innerR, j, len, outerR, ref, results1, rotation, scale, side, theme;
      ctx = this.ctx;
      theme = this._theme();
      ({
        outer: outerR,
        inner: innerR
      } = this.circleRadii(index));
      rotation = (circle.rotation || 0) + (this.globalRotation || 0); // degrees
      
      // Draw ring background (subtle shading for rotatable circles)
      if (circle.rotatable) {
        ctx.beginPath();
        ctx.arc(this.cx, this.cy, outerR, 0, 2 * Math.PI);
        ctx.arc(this.cx, this.cy, innerR, 0, 2 * Math.PI, true);
        ctx.fillStyle = theme.ringShade;
        ctx.fill();
      }
      // Draw ring borders
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, outerR, 0, 2 * Math.PI);
      ctx.strokeStyle = theme.ringBorder;
      ctx.lineWidth = 1;
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, innerR, 0, 2 * Math.PI);
      ctx.stroke();
      // Draw scales on this ring. When a ring carries scales on both edges,
      // each one only gets half the ring's width to grow into, so their ticks
      // and numerals (which extend inward from their own edge) don't meet and
      // overlap in the middle.
      hasBoth = (circle.outer != null) && circle.outer.visible !== false && (circle.inner != null) && circle.inner.visible !== false;
      ref = ['outer', 'inner'];
      results1 = [];
      for (j = 0, len = ref.length; j < len; j++) {
        side = ref[j];
        scale = circle[side];
        if (!((scale != null) && scale.visible !== false)) {
          continue;
        }
        results1.push(this._drawScale(scale, outerR, innerR, rotation, side, index, hasBoth));
      }
      return results1;
    }

    _drawScale(scale, outerR, innerR, rotation, side, ringIndex = 0, hasBoth = false) {
      var angle, angularOffset, approxLabelR, budget, candidate, candidates, clear, clearCandidate, ctx, d, diff, fontSize, isHalf, isOuter, j, l, label, labelAngle, labelFontSize, labelGap, labelHalfHeight, labelOffset, labelR, labelSlot, labelTotalAngle, lastLabelAngle, len, len1, len2, len3, letterFontSize, letterMinAngle, level, lineWidth, lr, lx, ly, m, maxTickLen, minLabelAngle, n, norm, occupied, occupiedAngles, prevOccupied, r1, r2, ringWidth, scaleLabelOffset, showLabel, sizeFactor, spread, step, tick, tickColor, tickDir, tickLen, tickRadius, ticks, totalAngle, x1, x2, y1, y2;
      if (scale.error) {
        return;
      }
      ctx = this.ctx;
      ticks = scale.generateTicks(this.minTickAngle || 1.5);
      isOuter = side === 'outer';
      tickRadius = isOuter ? outerR : innerR;
      // Inner-edge scales (on the inner boundary of a ring) point outward.
      // Outer-edge scales (on the outer boundary of a ring) point inward.
      // Thus adjacent rings face each other across a shared circle.
      tickDir = isOuter ? -1 : +1;
      ringWidth = outerR - innerR;
      budget = hasBoth ? ringWidth / 2 : ringWidth;
      // Labels must never collide: skip one that is too close to the previously
      // drawn label. The threshold is the angular width of a ~2-digit label.
      // Font size scales with the space available to this scale (itself derived
      // from viewport size), so text stays legible on small screens, shrinks
      // to fit when a ring hosts two scales, and stays proportionate on large
      // screens without any one label's extent exceeding its half of the ring.
      // The numeral sits beside its tick (angular offset) rather than beyond
      // its tip, so it costs almost no extra radial depth; it can afford to be
      // noticeably larger than when it had to fit within tickLen + full height.
      // A single-scale ring has twice the budget of a two-scale ring; use a
      // smaller factor for it so its numerals aren't disproportionately huge
      // compared to neighboring rings.
      sizeFactor = hasBoth ? 0.55 : 0.32;
      labelFontSize = Math.max(9, Math.min(24, budget * sizeFactor));
      letterFontSize = labelFontSize * (17 / 22);
      // Reserve room for the label past the tick tip so tick + label together
      // stay within this scale's half of the ring; otherwise, on a ring with
      // both an inner and an outer scale, the two sets of numerals meet and
      // overlap at the ring's midline. The label is vertically centered on its
      // anchor (textBaseline 'middle'), so roughly half its height reaches
      // further toward the ring's midline than the anchor point itself —
      // that half-height must be reserved too.
      labelGap = labelFontSize * 0.3 + 5;
      labelHalfHeight = labelFontSize * 0.4;
      maxTickLen = Math.max(6, Math.min(20, budget - labelGap - labelHalfHeight - 2));
      approxLabelR = tickRadius + tickDir * (maxTickLen + labelGap);
      minLabelAngle = (labelFontSize * 2 / approxLabelR) * 180 / Math.PI;
      lastLabelAngle = null;
      // The scale letter is drawn at the numeral radius, past the index tick;
      // reserve that angular slot so no numeral overlaps it. The offset is set
      // so the reserved slot's near edge clears the index tick (angle 0) by a
      // small margin, regardless of the letter's width.
      letterMinAngle = ((letterFontSize * 0.75 * scale.label.length + labelFontSize * 2) / 2 / approxLabelR) * 180 / Math.PI;
      // Stagger each ring/side's fixed label to a distinct angle. Without this,
      // every ring's letter (and adjacent numerals) would sit at the same
      // screen angle near the index tick and stack up radially into a jumble
      // whenever several rings share the same rotation (e.g. the default state).
      labelSlot = 2 * ringIndex + (isOuter ? 0 : 1);
      scaleLabelOffset = letterMinAngle + 2 + labelSlot * 12;
      // Built-in scale colors are dark grays meant for a white background —
      // invisible against dark mode's true black. Use white for ticks and
      // numerals there instead.
      tickColor = this.darkMode ? '#fff' : scale.color;
      // Numerals must never be hidden by the letter: find the nearest angle to
      // the preferred slot where the letter doesn't overlap any numeral that
      // will actually be drawn (rather than skip numerals near the letter).
      occupiedAngles = [];
      prevOccupied = null;
      for (j = 0, len = ticks.length; j < len; j++) {
        tick = ticks[j];
        if ((tick.level || 1) !== 1) {
          continue;
        }
        angle = scale.valueToAngle(tick.value);
        if (angle == null) {
          continue;
        }
        if (prevOccupied != null) {
          diff = Math.abs(angle - prevOccupied) % 360;
          if (diff > 180) {
            diff = 360 - diff;
          }
          if (diff < minLabelAngle) {
            continue;
          }
        }
        prevOccupied = angle;
        occupiedAngles.push(((angle + rotation) % 360 + 360) % 360);
      }
      labelOffset = scaleLabelOffset;
      step = 3;
      spread = 0;
      while (spread <= 60) {
        candidates = spread === 0 ? [scaleLabelOffset] : [scaleLabelOffset + spread, scaleLabelOffset - spread];
        clearCandidate = null;
        for (l = 0, len1 = candidates.length; l < len1; l++) {
          candidate = candidates[l];
          norm = ((candidate % 360) + 360) % 360;
          clear = true;
          for (m = 0, len2 = occupiedAngles.length; m < len2; m++) {
            occupied = occupiedAngles[m];
            d = Math.abs(norm - occupied) % 360;
            if (d > 180) {
              d = 360 - d;
            }
            if (d < letterMinAngle) {
              clear = false;
              break;
            }
          }
          if (clear) {
            clearCandidate = norm;
            break;
          }
        }
        if (clearCandidate != null) {
          labelOffset = clearCandidate;
          break;
        }
        spread += step;
      }
      for (n = 0, len3 = ticks.length; n < len3; n++) {
        tick = ticks[n];
        angle = scale.valueToAngle(tick.value);
        if (angle == null) {
          continue;
        }
        totalAngle = (angle + rotation - 90) * Math.PI / 180;
        level = tick.level || 1;
        // Highlight half-integer marks (e.g. 1.5, 2.5, ...) in red for readability
        isHalf = Math.abs((tick.value % 1) - 0.5) < 0.01;
        // Tick dimensions by level, scaled to fill the inter-ring gap
        if (level === 1) {
          tickLen = maxTickLen;
          lineWidth = 2.5;
          fontSize = labelFontSize;
          showLabel = true;
        } else if (level === 2) {
          tickLen = isHalf ? maxTickLen * 0.88 : maxTickLen * 0.65;
          lineWidth = isHalf ? 2.0 : 1.2;
          fontSize = 0;
          showLabel = false;
        } else {
          tickLen = maxTickLen * 0.4;
          lineWidth = 0.8;
          fontSize = 0;
          showLabel = false;
        }
        if (showLabel) {
          if (lastLabelAngle != null) {
            diff = Math.abs(angle - lastLabelAngle) % 360;
            if (diff > 180) {
              diff = 360 - diff;
            }
            showLabel = diff >= minLabelAngle;
          }
          if (showLabel) {
            lastLabelAngle = angle;
          }
        }
        ctx.strokeStyle = isHalf ? '#d00' : tickColor;
        ctx.lineWidth = lineWidth;
        // Draw the tick into its own ring, then place the label at the tip
        r1 = tickRadius;
        r2 = tickRadius + tickDir * tickLen;
        x1 = this.cx + r1 * Math.cos(totalAngle);
        y1 = this.cy + r1 * Math.sin(totalAngle);
        x2 = this.cx + r2 * Math.cos(totalAngle);
        y2 = this.cy + r2 * Math.sin(totalAngle);
        ctx.beginPath();
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
        if (showLabel) {
          // Place the label just past the tick's tip, with a clear radial gap,
          // and anchor it on its FIRST character (not its center) so multi-
          // character labels like "0.5" don't have their leading digit swing
          // back over the tick line.
          labelR = tickRadius + tickDir * (tickLen + labelGap);
          angularOffset = ((lineWidth / 2 + 2) / labelR) * (180 / Math.PI);
          labelTotalAngle = totalAngle + angularOffset * Math.PI / 180;
          lx = this.cx + labelR * Math.cos(labelTotalAngle);
          ly = this.cy + labelR * Math.sin(labelTotalAngle);
          ctx.save();
          ctx.translate(lx, ly);
          ctx.rotate(labelTotalAngle + Math.PI / 2);
          ctx.fillStyle = tickColor;
          ctx.font = 'bold ' + fontSize + 'px sans-serif';
          ctx.textAlign = 'left';
          ctx.textBaseline = 'middle';
          label = this._formatTickLabel(tick.value, scale);
          ctx.fillText(label, 0, 0);
          ctx.restore();
        }
      }
      // Draw the scale label at the numeral radius, past the index tick.
      // Each scale's letter sits at its own numeral radius, so outer and inner
      // scale letters on the same ring never overlap. The letter stays fixed
      // on screen (independent of rotation) so it doesn't wander as the user
      // turns a rotatable ring.
      labelAngle = (labelOffset - 90) * Math.PI / 180;
      lr = approxLabelR;
      lx = this.cx + lr * Math.cos(labelAngle);
      ly = this.cy + lr * Math.sin(labelAngle);
      ctx.save();
      ctx.translate(lx, ly);
      ctx.rotate(labelAngle + Math.PI / 2);
      ctx.fillStyle = 'rgba(40, 160, 40, 0.35)';
      ctx.font = 'bold ' + letterFontSize + 'px sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(scale.label, 0, 0);
      return ctx.restore();
    }

    _formatTickLabel(value, scale) {
      return formatTickLabel(value, scale);
    }

    _drawCursor() {
      var angle, ctx, r1, r2;
      ctx = this.ctx;
      angle = (this.cursorAngle - 90) * Math.PI / 180;
      r1 = 0;
      r2 = this.outerRadius + 8;
      ctx.beginPath();
      ctx.moveTo(this.cx + r1 * Math.cos(angle), this.cy + r1 * Math.sin(angle));
      ctx.lineTo(this.cx + r2 * Math.cos(angle), this.cy + r2 * Math.sin(angle));
      ctx.strokeStyle = '#ff4444';
      ctx.lineWidth = 2;
      ctx.stroke();
      // Cursor arrow at outer end
      ctx.beginPath();
      ctx.arc(this.cx + r2 * Math.cos(angle), this.cy + r2 * Math.sin(angle), 4, 0, 2 * Math.PI);
      ctx.fillStyle = '#ff4444';
      return ctx.fill();
    }

    // --- Pointer interaction ---
    _bindEvents() {
      this.canvas.addEventListener('pointerdown', (e) => {
        return this._onDown(e);
      });
      this.canvas.addEventListener('pointermove', (e) => {
        return this._onMove(e);
      });
      this.canvas.addEventListener('pointerup', (e) => {
        return this._onUp(e);
      });
      return this.canvas.addEventListener('pointercancel', (e) => {
        return this._onUp(e);
      });
    }

    _pointerPos(e) {
      var dx, dy, rect;
      rect = this.canvas.getBoundingClientRect();
      dx = e.clientX - rect.left - this.cx;
      dy = e.clientY - rect.top - this.cy;
      return {dx, dy};
    }

    _pointerAngle(e) {
      var angle, dx, dy;
      ({dx, dy} = this._pointerPos(e));
      angle = Math.atan2(dy, dx) * 180 / Math.PI + 90;
      return ((angle % 360) + 360) % 360;
    }

    _pointerRadius(e) {
      var dx, dy;
      ({dx, dy} = this._pointerPos(e));
      return Math.sqrt(dx * dx + dy * dy);
    }

    _onDown(e) {
      var angle, circle, hubR, i, inner, j, len, outer, radius, ref;
      // Ignore a second simultaneous touch (already dragging with another
      // pointer): leave it unclaimed and don't prevent its default behavior,
      // so a two-finger pinch is left for the browser to zoom natively.
      if (this.dragging != null) {
        return;
      }
      e.preventDefault();
      this.canvas.setPointerCapture(e.pointerId);
      angle = this._pointerAngle(e);
      radius = this._pointerRadius(e);
      ref = this.config;
      // Determine which ring the pointer is in
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        ({outer, inner} = this.circleRadii(i));
        if (radius >= inner && radius <= outer && circle.rotatable) {
          this.dragging = {
            type: 'circle',
            pointerId: e.pointerId,
            index: i,
            startAngle: angle,
            startRotation: circle.rotation || 0
          };
          return;
        }
      }
      ({
        // A drag inside the empty hub at the center rotates every ring together
        inner: hubR
      } = this.circleRadii(this.config.length - 1));
      if (this.config.length > 0 && radius < hubR) {
        this.dragging = {
          type: 'global',
          pointerId: e.pointerId,
          startAngle: angle,
          startRotation: this.globalRotation || 0
        };
        return;
      }
      // Otherwise, drag the cursor
      this.dragging = {
        type: 'cursor',
        pointerId: e.pointerId,
        startAngle: angle,
        startRotation: this.cursorAngle
      };
      this.cursorAngle = angle;
      this.render();
      return typeof this.onCursorMove === "function" ? this.onCursorMove(angle) : void 0;
    }

    _onMove(e) {
      var angle, circle, delta, ref, speed;
      if (((ref = this.dragging) != null ? ref.pointerId : void 0) !== e.pointerId) {
        return;
      }
      e.preventDefault();
      angle = this._pointerAngle(e);
      // In precise mode, the ring/cursor rotates at a tenth of the finger's
      // angular movement, for finer control on touchscreens.
      speed = this.precise ? 0.1 : 1;
      if (this.dragging.type === 'cursor') {
        delta = angle - this.dragging.startAngle;
        while (delta > 180) {
          delta -= 360;
        }
        while (delta < -180) {
          delta += 360;
        }
        this.cursorAngle = ((this.dragging.startAngle + delta * speed) % 360 + 360) % 360;
        this.render();
        return typeof this.onCursorMove === "function" ? this.onCursorMove(this.cursorAngle) : void 0;
      } else if (this.dragging.type === 'circle') {
        delta = angle - this.dragging.startAngle;
        // normalize delta to [-180, 180]
        while (delta > 180) {
          delta -= 360;
        }
        while (delta < -180) {
          delta += 360;
        }
        circle = this.config[this.dragging.index];
        circle.rotation = (this.dragging.startRotation + delta * speed + 360) % 360;
        this.render();
        return typeof this.onCircleRotate === "function" ? this.onCircleRotate(this.dragging.index, circle.rotation) : void 0;
      } else if (this.dragging.type === 'global') {
        delta = angle - this.dragging.startAngle;
        while (delta > 180) {
          delta -= 360;
        }
        while (delta < -180) {
          delta += 360;
        }
        this.globalRotation = (this.dragging.startRotation + delta * speed + 360) % 360;
        this.render();
        return typeof this.onGlobalRotate === "function" ? this.onGlobalRotate(this.globalRotation) : void 0;
      }
    }

    _onUp(e) {
      var ref;
      if (((ref = this.dragging) != null ? ref.pointerId : void 0) !== e.pointerId) {
        return;
      }
      return this.dragging = null;
    }

    // Read values at cursor position for all visible scales
    readAtCursor() {
      var circle, circleRotation, i, j, l, len, len1, ref, ref1, relAngle, results, scale, side, value;
      results = [];
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        circleRotation = circle.rotation || 0;
        ref1 = ['outer', 'inner'];
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          side = ref1[l];
          scale = circle[side];
          if (!((scale != null) && scale.visible !== false)) {
            continue;
          }
          if (scale.error) {
            continue;
          }
          // The cursor angle in the scale's reference frame
          relAngle = ((this.cursorAngle - circleRotation - (this.globalRotation || 0)) % 360 + 360) % 360;
          value = scale.angleToValue(relAngle);
          if ((value != null) && isFinite(value)) {
            results.push({
              scale: scale,
              value: value
            });
          }
        }
      }
      return results;
    }

  };

  // FlatRuler — same data model and public interface as CircularRuler (config,
  // cursorAngle, globalRotation, darkMode, precise, minTickAngle, callbacks,
  // readAtCursor), but rendered as horizontal bands that slide left/right
  // instead of rings that rotate. A ring's `rotation` (degrees) becomes a
  // horizontal offset: 360° == one full pass across `bandWidth` pixels, so the
  // tick pattern tiles/repeats as a band is dragged, like a real slide rule
  // opened flat.
  this.FlatRuler = class FlatRuler {
    constructor(canvas, config) {
      this.canvas = canvas;
      this.ctx = canvas.getContext('2d');
      this.config = config;
      this.cursorAngle = 0;
      this.globalRotation = 0;
      this.dpr = window.devicePixelRatio || 1;
      this.width = 0;
      this.height = 0;
      this.bandWidth = 0;
      this.bandHeight = 0;
      this.startY = 0;
      this.dragging = null;
      this.darkMode = false;
      this.precise = false;
      this.minTickAngle = 1.5;
      this.onCursorMove = null;
      this.onCircleRotate = null;
      this.onGlobalRotate = null;
      this._bindEvents();
      this.resize();
    }

    resize() {
      var nBands;
      this.width = window.innerWidth;
      this.height = window.innerHeight;
      if (this.width <= 0 || this.height <= 0) {
        requestAnimationFrame(() => {
          return this.resize();
        });
        return;
      }
      this.canvas.style.width = this.width + 'px';
      this.canvas.style.height = this.height + 'px';
      this.canvas.width = this.width * this.dpr;
      this.canvas.height = this.height * this.dpr;
      this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      // Zoom out slightly so one decade doesn't exactly fill the screen width
      // (which would put a tick flush against each edge); see FLAT_MARGIN_FRACTION.
      this.bandWidth = this.width / (1 + 2 * FLAT_MARGIN_FRACTION);
      this.marginPx = FLAT_MARGIN_FRACTION * this.bandWidth;
      // On a narrow screen, one decade's pixel width can be too tight for its
      // minor ticks; raise the angle threshold passed to generateTicks so it
      // thins out subdivisions accordingly (see FLAT_MIN_TICK_PX).
      this.effectiveMinTickAngle = Math.max(this.minTickAngle || 1.5, FLAT_MIN_TICK_PX * 360 / this.bandWidth);
      nBands = this.config.length;
      // Cap band height: unlike the circular layout (naturally bounded by
      // outerRadius), a tall/narrow viewport would otherwise stretch bands
      // across the whole screen, leaving mostly empty space around ticks
      // that are deliberately kept short and legible.
      this.bandHeight = Math.min(this.height / (nBands * 1.5 + 1), 110);
      this.startY = (this.height - nBands * this.bandHeight) / 2;
      return this.render();
    }

    bandYRange(index) {
      var top;
      top = this.startY + index * this.bandHeight;
      return {
        top: top,
        bottom: top + this.bandHeight
      };
    }

    _theme() {
      return themeFor(this.darkMode);
    }

    render() {
      var band, ctx, i, j, len, ref, theme;
      ctx = this.ctx;
      theme = this._theme();
      ctx.clearRect(0, 0, this.width, this.height);
      ctx.fillStyle = theme.bg;
      ctx.fillRect(0, 0, this.width, this.height);
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        band = ref[i];
        this._drawBand(i, band);
      }
      return this._drawCursor();
    }

    _drawBand(index, band) {
      var bottom, ctx, gripY, gx, hasBoth, j, l, len, len1, ref, ref1, results1, rotation, scale, side, theme, top;
      ctx = this.ctx;
      theme = this._theme();
      ({top, bottom} = this.bandYRange(index));
      rotation = (band.rotation || 0) + (this.globalRotation || 0);
      if (band.rotatable) {
        ctx.fillStyle = theme.ringShade;
        ctx.fillRect(0, top, this.width, bottom - top);
      } else {
        // Fixed band: draw a small grip at the left edge as a hint that
        // dragging anywhere on it moves every band together (global offset),
        // mirroring the circular ruler's empty center-hub drag.
        ctx.fillStyle = theme.ringBorder;
        gripY = (top + bottom) / 2;
        ref = [6, 12, 18];
        for (j = 0, len = ref.length; j < len; j++) {
          gx = ref[j];
          ctx.beginPath();
          ctx.arc(gx, gripY, 1.5, 0, 2 * Math.PI);
          ctx.fill();
        }
      }
      ctx.strokeStyle = theme.ringBorder;
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(0, top);
      ctx.lineTo(this.width, top);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(0, bottom);
      ctx.lineTo(this.width, bottom);
      ctx.stroke();
      hasBoth = (band.outer != null) && band.outer.visible !== false && (band.inner != null) && band.inner.visible !== false;
      ref1 = ['outer', 'inner'];
      results1 = [];
      for (l = 0, len1 = ref1.length; l < len1; l++) {
        side = ref1[l];
        scale = band[side];
        if (!((scale != null) && scale.visible !== false)) {
          continue;
        }
        results1.push(this._drawScaleBand(scale, top, bottom, rotation, side, hasBoth));
      }
      return results1;
    }

    _drawScaleBand(scale, top, bottom, rotation, side, hasBoth) {
      var angle, bandHeight, baseline, budget, ctx, fontSize, isHalf, isOuter, j, k, l, label, len, level, lineWidth, maxTickLen, phase, ref, repeats, showLabel, tick, tickColor, tickDir, tickLen, ticks, x;
      if (scale.error) {
        return;
      }
      ctx = this.ctx;
      ticks = scale.generateTicks(this.effectiveMinTickAngle || this.minTickAngle || 1.5);
      isOuter = side === 'outer';
      // Outer-edge scales sit on the band's top border and point down into it;
      // inner-edge scales sit on the bottom border and point up — so, like the
      // circular ruler, two adjacent bands' scales face each other.
      baseline = isOuter ? top : bottom;
      tickDir = isOuter ? 1 : -1;
      bandHeight = bottom - top;
      budget = hasBoth ? bandHeight / 2 : bandHeight;
      fontSize = Math.max(9, Math.min(20, budget * (hasBoth ? 0.5 : 0.3)));
      maxTickLen = Math.max(6, Math.min(18, budget - fontSize - 4));
      tickColor = this.darkMode ? '#fff' : scale.color;
      // Tile the tick pattern across the visible width so it reads as an
      // "infinite" ruler as the band is dragged past either edge.
      repeats = Math.ceil(this.width / this.bandWidth) + 2;
      for (j = 0, len = ticks.length; j < len; j++) {
        tick = ticks[j];
        angle = scale.valueToAngle(tick.value);
        if (angle == null) {
          continue;
        }
        phase = ((angle + rotation) % 360 + 360) % 360 / 360 * this.bandWidth;
        level = tick.level || 1;
        isHalf = Math.abs((tick.value % 1) - 0.5) < 0.01;
        if (level === 1) {
          tickLen = maxTickLen;
          lineWidth = 2.5;
          showLabel = true;
        } else if (level === 2) {
          tickLen = isHalf ? maxTickLen * 0.88 : maxTickLen * 0.65;
          lineWidth = isHalf ? 2.0 : 1.2;
          showLabel = false;
        } else {
          tickLen = maxTickLen * 0.4;
          lineWidth = 0.8;
          showLabel = false;
        }
        ctx.strokeStyle = isHalf ? '#d00' : tickColor;
        ctx.lineWidth = lineWidth;
        for (k = l = -1, ref = repeats; (-1 <= ref ? l <= ref : l >= ref); k = -1 <= ref ? ++l : --l) {
          x = phase + k * this.bandWidth + this.marginPx;
          if (x < -maxTickLen || x > this.width + maxTickLen) {
            continue;
          }
          ctx.beginPath();
          ctx.moveTo(x, baseline);
          ctx.lineTo(x, baseline + tickDir * tickLen);
          ctx.stroke();
          if (showLabel) {
            ctx.save();
            ctx.fillStyle = tickColor;
            ctx.font = 'bold ' + fontSize + 'px sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = isOuter ? 'top' : 'bottom';
            label = formatTickLabel(tick.value, scale);
            ctx.fillText(label, x, baseline + tickDir * (tickLen + 2));
            ctx.restore();
          }
        }
      }
      // Scale letter badge: fixed on screen near the left edge, independent of
      // rotation (mirrors the circular ruler's screen-fixed scale label).
      ctx.save();
      ctx.fillStyle = 'rgba(40, 160, 40, 0.5)';
      ctx.font = 'bold ' + fontSize + 'px sans-serif';
      ctx.textAlign = 'left';
      ctx.textBaseline = isOuter ? 'top' : 'bottom';
      ctx.fillText(scale.label, 24, baseline + tickDir * 2);
      return ctx.restore();
    }

    _drawCursor() {
      var ctx, x;
      ctx = this.ctx;
      x = ((this.cursorAngle % 360) + 360) % 360 / 360 * this.bandWidth + this.marginPx;
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, this.height);
      ctx.strokeStyle = '#ff4444';
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(x, this.height - 6, 4, 0, 2 * Math.PI);
      ctx.fillStyle = '#ff4444';
      return ctx.fill();
    }

    // --- Pointer interaction ---
    _bindEvents() {
      this.canvas.addEventListener('pointerdown', (e) => {
        return this._onDown(e);
      });
      this.canvas.addEventListener('pointermove', (e) => {
        return this._onMove(e);
      });
      this.canvas.addEventListener('pointerup', (e) => {
        return this._onUp(e);
      });
      return this.canvas.addEventListener('pointercancel', (e) => {
        return this._onUp(e);
      });
    }

    _pointerPos(e) {
      var rect;
      rect = this.canvas.getBoundingClientRect();
      return {
        x: e.clientX - rect.left,
        y: e.clientY - rect.top
      };
    }

    _onDown(e) {
      var band, bottom, i, j, len, ref, top, x, y;
      // Ignore a second simultaneous touch, same as the circular ruler.
      if (this.dragging != null) {
        return;
      }
      e.preventDefault();
      this.canvas.setPointerCapture(e.pointerId);
      ({x, y} = this._pointerPos(e));
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        band = ref[i];
        ({top, bottom} = this.bandYRange(i));
        if (!(y >= top && y <= bottom)) {
          continue;
        }
        if (band.rotatable) {
          this.dragging = {
            type: 'circle',
            pointerId: e.pointerId,
            index: i,
            startX: x,
            startRotation: band.rotation || 0
          };
        } else {
          // Fixed band: drag it to move every band together.
          this.dragging = {
            type: 'global',
            pointerId: e.pointerId,
            startX: x,
            startRotation: this.globalRotation || 0
          };
        }
        return;
      }
      // Outside any band (e.g. above/below the stack): drag the cursor.
      this.dragging = {
        type: 'cursor',
        pointerId: e.pointerId,
        startX: x,
        startRotation: this.cursorAngle
      };
      this.cursorAngle = ((x - this.marginPx) / this.bandWidth * 360 % 360 + 360) % 360;
      this.render();
      return typeof this.onCursorMove === "function" ? this.onCursorMove(this.cursorAngle) : void 0;
    }

    _onMove(e) {
      var band, degDelta, ref, speed, x;
      if (((ref = this.dragging) != null ? ref.pointerId : void 0) !== e.pointerId) {
        return;
      }
      e.preventDefault();
      ({x} = this._pointerPos(e));
      // In precise mode, move at a tenth of the finger's actual movement, same
      // as the circular ruler.
      speed = this.precise ? 0.1 : 1;
      degDelta = (x - this.dragging.startX) / this.bandWidth * 360 * speed;
      if (this.dragging.type === 'cursor') {
        this.cursorAngle = ((this.dragging.startRotation + degDelta) % 360 + 360) % 360;
        this.render();
        return typeof this.onCursorMove === "function" ? this.onCursorMove(this.cursorAngle) : void 0;
      } else if (this.dragging.type === 'circle') {
        band = this.config[this.dragging.index];
        band.rotation = ((this.dragging.startRotation + degDelta) % 360 + 360) % 360;
        this.render();
        return typeof this.onCircleRotate === "function" ? this.onCircleRotate(this.dragging.index, band.rotation) : void 0;
      } else if (this.dragging.type === 'global') {
        this.globalRotation = ((this.dragging.startRotation + degDelta) % 360 + 360) % 360;
        this.render();
        return typeof this.onGlobalRotate === "function" ? this.onGlobalRotate(this.globalRotation) : void 0;
      }
    }

    _onUp(e) {
      var ref;
      if (((ref = this.dragging) != null ? ref.pointerId : void 0) !== e.pointerId) {
        return;
      }
      return this.dragging = null;
    }

    // Read values at cursor position for all visible scales — identical logic
    // to CircularRuler.readAtCursor, since both share the same degrees-based
    // data model.
    readAtCursor() {
      var circle, circleRotation, i, j, l, len, len1, ref, ref1, relAngle, results, scale, side, value;
      results = [];
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        circleRotation = circle.rotation || 0;
        ref1 = ['outer', 'inner'];
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          side = ref1[l];
          scale = circle[side];
          if (!((scale != null) && scale.visible !== false)) {
            continue;
          }
          if (scale.error) {
            continue;
          }
          relAngle = ((this.cursorAngle - circleRotation - (this.globalRotation || 0)) % 360 + 360) % 360;
          value = scale.angleToValue(relAngle);
          if ((value != null) && isFinite(value)) {
            results.push({
              scale: scale,
              value: value
            });
          }
        }
      }
      return results;
    }

  };

}).call(this);
