// Generated by CoffeeScript 2.7.0
(function() {
  // ruler.coffee — Canvas rendering + pointer interaction for circular slide rule
  this.CircularRuler = class CircularRuler {
    constructor(canvas, config) {
      this.canvas = canvas;
      this.ctx = canvas.getContext('2d');
      this.config = config; // array of circle objects
      this.cursorAngle = 0; // degrees, 0 = top (12 o'clock)
      this.dpr = window.devicePixelRatio || 1;
      this.width = 0;
      this.height = 0;
      this.cx = 0;
      this.cy = 0;
      this.outerRadius = 0;
      this.ringWidth = 0;
      this.dragging = null; // {type: 'circle'|'cursor', index, startAngle, startRotation}
      this.onCursorMove = null; // callback(angle)
      this.onCircleRotate = null; // callback(index, angle)
      this._bindEvents();
      this.resize();
    }

    resize() {
      var nCircles;
      this.width = window.innerWidth;
      this.height = window.innerHeight;
      this.canvas.style.width = this.width + 'px';
      this.canvas.style.height = this.height + 'px';
      this.canvas.width = this.width * this.dpr;
      this.canvas.height = this.height * this.dpr;
      this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      this.cx = this.width / 2;
      this.cy = this.height / 2;
      this.outerRadius = Math.min(this.width, this.height) / 2 - 8;
      nCircles = this.config.length;
      this.ringWidth = this.outerRadius / (nCircles * 1.5 + 1);
      return this.render();
    }

    // Get radius range for a circle index
    circleRadii(index) {
      var innerR, outerR;
      outerR = this.outerRadius - index * this.ringWidth;
      innerR = outerR - this.ringWidth;
      return {
        outer: outerR,
        inner: innerR
      };
    }

    render() {
      var circle, ctx, i, j, len, ref;
      ctx = this.ctx;
      ctx.clearRect(0, 0, this.width, this.height);
      // Draw background circle
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, this.outerRadius + 4, 0, 2 * Math.PI);
      ctx.fillStyle = '#fff';
      ctx.fill();
      ctx.strokeStyle = '#999';
      ctx.lineWidth = 1;
      ctx.stroke();
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        this._drawCircle(i, circle);
      }
      return this._drawCursor();
    }

    _drawCircle(index, circle) {
      var ctx, innerR, j, len, outerR, ref, results1, rotation, scale, side;
      ctx = this.ctx;
      ({
        outer: outerR,
        inner: innerR
      } = this.circleRadii(index));
      rotation = circle.rotation || 0; // degrees
      
      // Draw ring background (subtle shading for rotatable circles)
      if (circle.rotatable) {
        ctx.beginPath();
        ctx.arc(this.cx, this.cy, outerR, 0, 2 * Math.PI);
        ctx.arc(this.cx, this.cy, innerR, 0, 2 * Math.PI, true);
        ctx.fillStyle = 'rgba(0,0,0,0.02)';
        ctx.fill();
      }
      // Draw ring borders
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, outerR, 0, 2 * Math.PI);
      ctx.strokeStyle = '#bbb';
      ctx.lineWidth = 1;
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(this.cx, this.cy, innerR, 0, 2 * Math.PI);
      ctx.stroke();
      ref = ['outer', 'inner'];
      // Draw scales on this ring
      results1 = [];
      for (j = 0, len = ref.length; j < len; j++) {
        side = ref[j];
        scale = circle[side];
        if (!((scale != null) && scale.visible !== false)) {
          continue;
        }
        results1.push(this._drawScale(scale, outerR, innerR, rotation, side));
      }
      return results1;
    }

    _drawScale(scale, outerR, innerR, rotation, side) {
      var angle, approxLabelR, ctx, diff, fontSize, isHalf, isOuter, j, label, labelAngle, labelFontSize, labelOffset, labelR, lastLabelAngle, len, letterDiff, letterMinAngle, level, lineWidth, lr, lx, ly, maxTickLen, minLabelAngle, r1, r2, ringWidth, scaleLabelOffset, showLabel, tick, tickDir, tickLen, tickRadius, ticks, totalAngle, x1, x2, y1, y2;
      if (scale.error) {
        return;
      }
      ctx = this.ctx;
      ticks = scale.generateTicks(this.minTickAngle || 1.5);
      isOuter = side === 'outer';
      tickRadius = isOuter ? outerR : innerR;
      // Inner-edge scales (on the inner boundary of a ring) point outward.
      // Outer-edge scales (on the outer boundary of a ring) point inward.
      // Thus adjacent rings face each other across a shared circle.
      tickDir = isOuter ? -1 : +1;
      ringWidth = outerR - innerR;
      maxTickLen = Math.max(6, Math.min(20, ringWidth - 8));
      // Labels must never collide: skip one that is too close to the previously
      // drawn label. The threshold is the angular width of a ~2-digit label.
      labelFontSize = 22;
      approxLabelR = tickRadius + tickDir * (maxTickLen + labelFontSize / 2 + 4);
      minLabelAngle = (labelFontSize * 2 / approxLabelR) * 180 / Math.PI;
      lastLabelAngle = null;
      // The scale letter is drawn at the numeral radius, a few degrees past the
      // index tick; reserve that angular slot so no numeral overlaps it
      scaleLabelOffset = 5;
      letterMinAngle = ((17 * 0.75 * scale.label.length + labelFontSize * 2) / 2 / approxLabelR) * 180 / Math.PI;
      for (j = 0, len = ticks.length; j < len; j++) {
        tick = ticks[j];
        angle = scale.valueToAngle(tick.value);
        if (angle == null) {
          continue;
        }
        totalAngle = (angle + rotation - 90) * Math.PI / 180;
        level = tick.level || 1;
        // Highlight half-integer marks (e.g. 1.5, 2.5, ...) in red for readability
        isHalf = Math.abs((tick.value % 1) - 0.5) < 0.01;
        // Tick dimensions by level, scaled to fill the inter-ring gap
        if (level === 1) {
          tickLen = maxTickLen;
          lineWidth = 2.5;
          fontSize = labelFontSize;
          showLabel = true;
        } else if (level === 2) {
          tickLen = isHalf ? maxTickLen * 0.88 : maxTickLen * 0.65;
          lineWidth = isHalf ? 2.0 : 1.2;
          fontSize = 0;
          showLabel = false;
        } else {
          tickLen = maxTickLen * 0.4;
          lineWidth = 0.8;
          fontSize = 0;
          showLabel = false;
        }
        if (showLabel) {
          if (lastLabelAngle != null) {
            diff = Math.abs(angle - lastLabelAngle) % 360;
            if (diff > 180) {
              diff = 360 - diff;
            }
            showLabel = diff >= minLabelAngle;
          }
          // Keep numerals clear of the scale letter's reserved slot
          if (showLabel) {
            letterDiff = Math.abs(angle - scaleLabelOffset) % 360;
            if (letterDiff > 180) {
              letterDiff = 360 - letterDiff;
            }
            showLabel = letterDiff >= letterMinAngle;
          }
          if (showLabel) {
            lastLabelAngle = angle;
          }
        }
        ctx.strokeStyle = isHalf ? '#d00' : scale.color;
        ctx.lineWidth = lineWidth;
        // Draw the tick into its own ring, then place the label at the tip
        r1 = tickRadius;
        r2 = tickRadius + tickDir * tickLen;
        x1 = this.cx + r1 * Math.cos(totalAngle);
        y1 = this.cy + r1 * Math.sin(totalAngle);
        x2 = this.cx + r2 * Math.cos(totalAngle);
        y2 = this.cy + r2 * Math.sin(totalAngle);
        ctx.beginPath();
        ctx.moveTo(x1, y1);
        ctx.lineTo(x2, y2);
        ctx.stroke();
        if (showLabel) {
          // Place the label inside the ring, at the tip of the tick
          labelOffset = fontSize / 2 + 4;
          labelR = tickRadius + tickDir * (tickLen + labelOffset);
          lx = this.cx + labelR * Math.cos(totalAngle);
          ly = this.cy + labelR * Math.sin(totalAngle);
          ctx.save();
          ctx.translate(lx, ly);
          ctx.rotate(totalAngle + Math.PI / 2);
          ctx.fillStyle = scale.color;
          ctx.font = 'bold ' + fontSize + 'px sans-serif';
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          label = this._formatTickLabel(tick.value, scale);
          ctx.fillText(label, 0, 0);
          ctx.restore();
        }
      }
      // Draw the scale label at the numeral radius, past the index tick.
      // Each scale's letter sits at its own numeral radius, so outer and inner
      // scale letters on the same ring never overlap.
      labelAngle = (rotation + scaleLabelOffset - 90) * Math.PI / 180;
      lr = approxLabelR;
      lx = this.cx + lr * Math.cos(labelAngle);
      ly = this.cy + lr * Math.sin(labelAngle);
      ctx.save();
      ctx.translate(lx, ly);
      ctx.rotate(labelAngle + Math.PI / 2);
      ctx.fillStyle = 'rgba(40, 160, 40, 0.35)';
      ctx.font = 'bold 17px sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(scale.label, 0, 0);
      return ctx.restore();
    }

    _formatTickLabel(value, scale) {
      if (scale.formula.indexOf('sin') >= 0 || scale.formula.indexOf('tan') >= 0) {
        if (value < 1) {
          return value.toFixed(2) + '°';
        } else if (value < 10) {
          return value.toFixed(1) + '°';
        } else {
          return Math.round(value).toString() + '°';
        }
      } else if (scale.formula.indexOf('log10') >= 0 || scale.formula.indexOf('log(') >= 0) {
        // Log scales: integers without trailing zeros
        if (value >= 1) {
          return Math.round(value).toString();
        } else {
          // Sub-1 values (e.g. sqrt scale): show with one decimal
          return value.toFixed(1);
        }
      } else {
        // Linear and other scales: no non-significant trailing zeros
        if (value >= 100) {
          return Math.round(value).toString();
        } else if (value >= 10) {
          return value.toFixed(0);
        } else if (value >= 1) {
          return parseFloat(value.toFixed(1)).toString();
        } else {
          return parseFloat(value.toFixed(2)).toString();
        }
      }
    }

    _drawCursor() {
      var angle, ctx, r1, r2;
      ctx = this.ctx;
      angle = (this.cursorAngle - 90) * Math.PI / 180;
      r1 = 0;
      r2 = this.outerRadius + 8;
      ctx.beginPath();
      ctx.moveTo(this.cx + r1 * Math.cos(angle), this.cy + r1 * Math.sin(angle));
      ctx.lineTo(this.cx + r2 * Math.cos(angle), this.cy + r2 * Math.sin(angle));
      ctx.strokeStyle = '#ff4444';
      ctx.lineWidth = 2;
      ctx.stroke();
      // Cursor arrow at outer end
      ctx.beginPath();
      ctx.arc(this.cx + r2 * Math.cos(angle), this.cy + r2 * Math.sin(angle), 4, 0, 2 * Math.PI);
      ctx.fillStyle = '#ff4444';
      return ctx.fill();
    }

    // --- Pointer interaction ---
    _bindEvents() {
      this.canvas.addEventListener('pointerdown', (e) => {
        return this._onDown(e);
      });
      this.canvas.addEventListener('pointermove', (e) => {
        return this._onMove(e);
      });
      this.canvas.addEventListener('pointerup', (e) => {
        return this._onUp(e);
      });
      return this.canvas.addEventListener('pointercancel', (e) => {
        return this._onUp(e);
      });
    }

    _pointerPos(e) {
      var dx, dy, rect;
      rect = this.canvas.getBoundingClientRect();
      dx = e.clientX - rect.left - this.cx;
      dy = e.clientY - rect.top - this.cy;
      return {dx, dy};
    }

    _pointerAngle(e) {
      var angle, dx, dy;
      ({dx, dy} = this._pointerPos(e));
      angle = Math.atan2(dy, dx) * 180 / Math.PI + 90;
      return ((angle % 360) + 360) % 360;
    }

    _pointerRadius(e) {
      var dx, dy;
      ({dx, dy} = this._pointerPos(e));
      return Math.sqrt(dx * dx + dy * dy);
    }

    _onDown(e) {
      var angle, circle, i, inner, j, len, outer, radius, ref;
      e.preventDefault();
      this.canvas.setPointerCapture(e.pointerId);
      angle = this._pointerAngle(e);
      radius = this._pointerRadius(e);
      ref = this.config;
      // Determine which ring the pointer is in
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        ({outer, inner} = this.circleRadii(i));
        if (radius >= inner && radius <= outer && circle.rotatable) {
          this.dragging = {
            type: 'circle',
            index: i,
            startAngle: angle,
            startRotation: circle.rotation || 0
          };
          return;
        }
      }
      // Otherwise, drag the cursor
      this.dragging = {
        type: 'cursor',
        startAngle: angle,
        startRotation: this.cursorAngle
      };
      this.cursorAngle = angle;
      this.render();
      return typeof this.onCursorMove === "function" ? this.onCursorMove(angle) : void 0;
    }

    _onMove(e) {
      var angle, circle, delta;
      if (!this.dragging) {
        return;
      }
      e.preventDefault();
      angle = this._pointerAngle(e);
      if (this.dragging.type === 'cursor') {
        this.cursorAngle = angle;
        this.render();
        return typeof this.onCursorMove === "function" ? this.onCursorMove(angle) : void 0;
      } else if (this.dragging.type === 'circle') {
        delta = angle - this.dragging.startAngle;
        // normalize delta to [-180, 180]
        while (delta > 180) {
          delta -= 360;
        }
        while (delta < -180) {
          delta += 360;
        }
        circle = this.config[this.dragging.index];
        circle.rotation = (this.dragging.startRotation + delta + 360) % 360;
        this.render();
        return typeof this.onCircleRotate === "function" ? this.onCircleRotate(this.dragging.index, circle.rotation) : void 0;
      }
    }

    _onUp(e) {
      return this.dragging = null;
    }

    // Read values at cursor position for all visible scales
    readAtCursor() {
      var circle, circleRotation, i, j, k, len, len1, ref, ref1, relAngle, results, scale, side, value;
      results = [];
      ref = this.config;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        circle = ref[i];
        circleRotation = circle.rotation || 0;
        ref1 = ['outer', 'inner'];
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          side = ref1[k];
          scale = circle[side];
          if (!((scale != null) && scale.visible !== false)) {
            continue;
          }
          if (scale.error) {
            continue;
          }
          // The cursor angle in the scale's reference frame
          relAngle = ((this.cursorAngle - circleRotation) % 360 + 360) % 360;
          value = scale.angleToValue(relAngle);
          if ((value != null) && isFinite(value)) {
            results.push({
              scale: scale,
              value: value
            });
          }
        }
      }
      return results;
    }

  };

}).call(this);
