// Generated by CoffeeScript 2.7.0
(function() {
  // scales.coffee — Generic Scale class + built-in scale definitions
  this.Scale = class Scale {
    constructor(opts) {
      var derived;
      this.label = opts.label || '?';
      this.formula = opts.formula || 'Math.log10(x)';
      this.range = opts.range || [1, 10];
      this.decades = opts.decades || null;
      this.color = opts.color || '#e0e0e0';
      this.side = opts.side || 'outer';
      this.ticks = opts.ticks || 'auto';
      this.builtin = opts.builtin || false;
      this.error = null;
      this.fn = null;
      this.compile();
      // Default: the range spans exactly one full circle. Specify decades only
      // when the angular scale must differ (e.g. S/T/ST stay aligned with D).
      this.decadesAuto = opts.decades == null;
      if (this.decadesAuto) {
        derived = Math.abs(this.eval(this.range[1]) - this.eval(this.range[0]));
        this.decades = isFinite(derived) && derived > 0 ? derived : 1;
      }
    }

    compile() {
      var e, mid, testVal;
      this.error = null;
      try {
        this.fn = new Function('x', 'Math', 'return ' + this.formula + ';');
        // quick sanity check
        testVal = this.eval(this.range[0]);
        if (!isFinite(testVal)) {
          // try mid-range
          mid = (this.range[0] + this.range[1]) / 2;
          testVal = this.eval(mid);
        }
        if (!isFinite(testVal)) {
          return this.error = 'Formula produces no finite values in range';
        }
      } catch (error) {
        e = error;
        this.error = e.message;
        return this.fn = null;
      }
    }

    eval(x) {
      var e, val;
      if (!this.fn) {
        return 0/0;
      }
      try {
        val = this.fn(x, Math);
        if (typeof val === 'number') {
          return val;
        } else {
          return 0/0;
        }
      } catch (error) {
        e = error;
        return 0/0;
      }
    }

    // Convert a value to an angle in degrees [0, 360)
    valueToAngle(x) {
      var angle, basePos, pos;
      pos = this.eval(x);
      if (!isFinite(pos)) {
        return null;
      }
      basePos = this.eval(this.range[0]);
      if (!isFinite(basePos)) {
        return null;
      }
      angle = 360 * (pos - basePos) / this.decades;
      // normalize to [0, 360)
      angle = ((angle % 360) + 360) % 360;
      return angle;
    }

    // Convert an angle back to a value (inverse via bisection)
    angleToValue(angle) {
      var basePos, hi, i, l, lo, mid, targetPos, val;
      if (!this.fn) {
        return null;
      }
      basePos = this.eval(this.range[0]);
      if (!isFinite(basePos)) {
        return null;
      }
      targetPos = basePos + angle * this.decades / 360;
      // bisection: find x such that eval(x) = targetPos
      lo = this.range[0];
      hi = this.range[1];
      for (i = l = 0; l <= 60; i = ++l) {
        mid = (lo + hi) / 2;
        val = this.eval(mid);
        if (!isFinite(val)) {
          return null;
        }
        if (val < targetPos) {
          lo = mid;
        } else {
          hi = mid;
        }
      }
      return (lo + hi) / 2;
    }

    // Generate tick marks; minAngle (degrees) filters ticks too close together
    generateTicks(minAngle = 1.5) {
      if (Array.isArray(this.ticks)) {
        return this.ticks;
      }
      return this.autoTicks(minAngle);
    }

    autoTicks(minAngle = 1.5) {
      var max, min;
      [min, max] = this.range;
      // Determine tick density based on scale type
      if (this.formula.indexOf('log10') >= 0 || this.formula.indexOf('log(') >= 0) {
        return this._logTicks(min, max, minAngle);
      } else {
        return this._linearTicks(min, max, minAngle);
      }
    }

    // Largest subdivision count in [10, 5, 2] whose ticks stay >= minAngle apart.
    // 10% tolerance: minAngle is a readability target, not a hard limit —
    // without it, a 2.99° segment loses its midpoint tick for 0.01°.
    _subdivCount(angle, minAngle) {
      var l, len, n, ref;
      ref = [10, 5, 2];
      for (l = 0, len = ref.length; l < len; l++) {
        n = ref[l];
        if (angle / n >= minAngle * 0.9) {
          return n;
        }
      }
      return 0;
    }

    _logTicks(min, max, minAngle = 1.5) {
      var a1, a2, base, d, endDec, i, j, k, l, l2Count, l2Positions, l2val, l3Count, l3val, m, nextVal, o, p, q, ref, ref1, ref2, ref3, ref4, seg, segAngle, segEnd, segStart, startDec, subAngle, ticks, val;
      // Support reversed ranges (e.g. sqrt scale where values decrease as angle increases)
      if (min > max) {
        [min, max] = [max, min];
      }
      ticks = [];
      // 3-level hierarchy for log scales with adaptive subdivision:
      // Level 1 (major): integers x 10^d — long, labeled
      // Level 2 (medium): 1/10, 1/5, or 1/2 subdivisions — medium, no label
      // Level 3 (minor): further subdivisions — short
      // Subdivision density adapts to available angular space (minAngle).
      startDec = Math.floor(Math.log10(min));
      endDec = Math.ceil(Math.log10(max)) - 1;
      for (d = l = ref = startDec, ref1 = endDec; (ref <= ref1 ? l <= ref1 : l >= ref1); d = ref <= ref1 ? ++l : --l) {
        base = Math.pow(10, d);
        for (i = m = 1; m <= 9; i = ++m) {
          val = base * i;
          nextVal = i === 9 ? base * 10 : base * (i + 1);
          if (val >= max) {
            continue;
          }
          if (val >= min) {
            ticks.push({
              value: val,
              level: 1
            });
          }
          // Angular span of this integer segment (use actual formula, not assumed log10)
          a1 = this.valueToAngle(val);
          a2 = this.valueToAngle(nextVal);
          segAngle = Math.abs(a2 - a1);
          if (segAngle > 180) {
            segAngle = 360 - segAngle;
          }
          // Choose level 2 subdivision count (prefer 10, fall back to 5, then 2)
          l2Count = this._subdivCount(segAngle, minAngle);
          if (!(l2Count > 0)) {
            continue;
          }
          // Build level 2 tick positions (including segment boundaries for level 3)
          l2Positions = [val];
          for (j = o = 1, ref2 = l2Count; (1 <= ref2 ? o < ref2 : o > ref2); j = 1 <= ref2 ? ++o : --o) {
            l2val = base * (i + j / l2Count);
            l2Positions.push(l2val);
            if (l2val >= min && l2val < max) {
              ticks.push({
                value: l2val,
                level: 2
              });
            }
          }
          l2Positions.push(nextVal);
          // Level 3: sub-subdivisions within each level-2 sub-segment
          subAngle = segAngle / l2Count;
          l3Count = this._subdivCount(subAngle, minAngle);
          if (l3Count > 0) {
            for (seg = p = 0, ref3 = l2Count; (0 <= ref3 ? p < ref3 : p > ref3); seg = 0 <= ref3 ? ++p : --p) {
              segStart = l2Positions[seg];
              segEnd = l2Positions[seg + 1];
              for (k = q = 1, ref4 = l3Count; (1 <= ref4 ? q < ref4 : q > ref4); k = 1 <= ref4 ? ++q : --q) {
                l3val = segStart + (segEnd - segStart) * k / l3Count;
                if (l3val >= min && l3val < max) {
                  ticks.push({
                    value: l3val,
                    level: 3
                  });
                }
              }
            }
          }
        }
      }
      ticks.sort(function(a, b) {
        return a.value - b.value;
      });
      return ticks;
    }

    _linearTicks(min, max, minAngle = 1.5) {
      var j, k, l, l2Count, l2val, l3Count, l3val, m, ref, ref1, segEnd, segStart, span, step, stepAngle, ticks, val;
      if (min > max) {
        [min, max] = [max, min];
      }
      ticks = [];
      span = max - min;
      if (span <= 1) {
        step = 0.1;
      } else if (span <= 10) {
        step = 1;
      } else if (span <= 100) {
        step = 10;
      } else {
        step = Math.pow(10, Math.floor(Math.log10(span)));
      }
      // Angular span per step
      stepAngle = 360 * step / (span * this.decades);
      // Choose subdivision based on minAngle
      l2Count = this._subdivCount(stepAngle, minAngle);
      l3Count = l2Count > 0 ? this._subdivCount(stepAngle / l2Count, minAngle) : 0;
      val = Math.ceil(min / step) * step;
      // Epsilon guards against float accumulation (0.1 * 10 < 1)
      while (val < max - 1e-9) {
        ticks.push({
          value: val,
          level: 1
        });
        if (l2Count > 0) {
          for (j = l = 1, ref = l2Count; (1 <= ref ? l < ref : l > ref); j = 1 <= ref ? ++l : --l) {
            l2val = val + step * j / l2Count;
            if (l2val < max) {
              ticks.push({
                value: l2val,
                level: 2
              });
            }
            if (l3Count > 0) {
              segStart = val + step * (j - 1) / l2Count;
              segEnd = l2val;
              for (k = m = 1, ref1 = l3Count; (1 <= ref1 ? m < ref1 : m > ref1); k = 1 <= ref1 ? ++m : --m) {
                l3val = segStart + (segEnd - segStart) * k / l3Count;
                if (l3val < max) {
                  ticks.push({
                    value: l3val,
                    level: 3
                  });
                }
              }
            }
          }
        }
        val += step;
      }
      return ticks;
    }

    toJSON() {
      return {
        label: this.label,
        formula: this.formula,
        range: this.range,
        decades: this.decades,
        color: this.color,
        side: this.side,
        ticks: this.ticks,
        builtin: this.builtin
      };
    }

  };

  // Built-in scale definitions
  this.BUILTIN_SCALES = [
    new Scale({
      label: 'D',
      formula: 'Math.log10(x)',
      range: [1,
    10],
      color: '#111',
      side: 'outer',
      builtin: true
    }),
    new Scale({
      label: 'C',
      formula: 'Math.log10(x)',
      range: [1,
    10],
      color: '#111',
      side: 'inner',
      builtin: true
    }),
    new Scale({
      label: 'A',
      formula: 'Math.log10(x) / 2',
      range: [1,
    100],
      color: '#444',
      side: 'outer',
      builtin: true
    }),
    new Scale({
      label: 'B',
      formula: 'Math.log10(x) / 2',
      range: [1,
    100],
      color: '#444',
      side: 'inner',
      builtin: true
    }),
    new Scale({
      label: 'K',
      formula: 'Math.log10(x) / 3',
      range: [1,
    1000],
      color: '#666',
      side: 'inner',
      builtin: true
    }),
    new Scale({
      label: 'L',
      formula: 'x',
      range: [0,
    1],
      color: '#666',
      side: 'outer',
      builtin: true
    }),
    new Scale({
      label: 'S',
      formula: 'Math.log10(Math.sin(x * Math.PI / 180))',
      range: [5.7,
    90],
      decades: 1,
      color: '#888',
      side: 'outer',
      builtin: true
    }),
    new Scale({
      label: 'T',
      formula: 'Math.log10(Math.tan(x * Math.PI / 180))',
      range: [5.7,
    45],
      decades: 1,
      color: '#888',
      side: 'inner',
      builtin: true
    }),
    new Scale({
      label: 'ST',
      formula: 'Math.log10(Math.sin(x * Math.PI / 180))',
      range: [0.57,
    5.7],
      decades: 1,
      color: '#888',
      side: 'inner',
      builtin: true
    }),
    new Scale({
      label: 'sqrt',
      formula: 'Math.log10(Math.sqrt(1 - .01 * x * x))',
      range: [Math.sqrt(99),
    0.1],
      color: '#c44',
      side: 'outer',
      builtin: true
    })
  ];

}).call(this);
