// Generated by CoffeeScript 2.7.0
(function() {
  // sw.coffee — Service worker for offline PWA
  var ASSETS, CACHE_NAME;

  CACHE_NAME = 'slide-rule-v54';

  ASSETS = ['./', './index.html', './styles.css', './scales.js', './ruler.js', './app.js', './manifest.json'];

  self.addEventListener('install', function(event) {
    return event.waitUntil(caches.open(CACHE_NAME).then(function(cache) {
      return cache.addAll(ASSETS);
    }).then(function() {
      if (!self.registration.active) {
        // Activate immediately on the very first install (nothing to preserve).
        // On a later update, wait for the client to confirm via the "update
        // available" button, which triggers activation through postMessage.
        return self.skipWaiting();
      }
    }));
  });

  self.addEventListener('message', function(event) {
    if (event.data === 'skipWaiting') {
      return self.skipWaiting();
    }
  });

  self.addEventListener('activate', function(event) {
    return event.waitUntil(caches.keys().then(function(keys) {
      return Promise.all(keys.filter(function(key) {
        return key !== CACHE_NAME;
      }).map(function(key) {
        return caches.delete(key);
      }));
    }).then(function() {
      return self.clients.claim();
    }));
  });

  self.addEventListener('fetch', function(event) {
    return event.respondWith(caches.match(event.request).then(function(cached) {
      if (cached) {
        return cached;
      } else {
        return fetch(event.request).then(function(response) {
          var clone;
          // Cache new responses for same-origin GET
          if (event.request.method === 'GET' && response.ok && event.request.url.indexOf(self.location.origin) === 0) {
            clone = response.clone();
            caches.open(CACHE_NAME).then(function(cache) {
              return cache.put(event.request, clone);
            });
          }
          return response;
        }).catch(function() {
          // Offline fallback
          return caches.match('./index.html');
        });
      }
    }));
  });

}).call(this);
